(cl:defpackage lili_audio-msg
  (:use )
  (:export
   "<TTSACTION>"
   "TTSACTION"
   "<TTSACTIONFEEDBACK>"
   "TTSACTIONFEEDBACK"
   "<TTSACTIONGOAL>"
   "TTSACTIONGOAL"
   "<TTSACTIONRESULT>"
   "TTSACTIONRESULT"
   "<TTSFEEDBACK>"
   "TTSFEEDBACK"
   "<TTSGOAL>"
   "TTSGOAL"
   "<TTSRESULT>"
   "TTSRESULT"
  ))

