; Auto-generated. Do not edit!


(cl:in-package lili_audio-msg)


;//! \htmlinclude TTSResult.msg.html

(cl:defclass <TTSResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TTSResult (<TTSResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TTSResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TTSResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lili_audio-msg:<TTSResult> is deprecated: use lili_audio-msg:TTSResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TTSResult>) ostream)
  "Serializes a message object of type '<TTSResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TTSResult>) istream)
  "Deserializes a message object of type '<TTSResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TTSResult>)))
  "Returns string type for a message object of type '<TTSResult>"
  "lili_audio/TTSResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TTSResult)))
  "Returns string type for a message object of type 'TTSResult"
  "lili_audio/TTSResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TTSResult>)))
  "Returns md5sum for a message object of type '<TTSResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TTSResult)))
  "Returns md5sum for a message object of type 'TTSResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TTSResult>)))
  "Returns full string definition for message of type '<TTSResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TTSResult)))
  "Returns full string definition for message of type 'TTSResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TTSResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TTSResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TTSResult
))
