// Generated by gencpp from file lili_audio/RecognizeSpeech.msg
// DO NOT EDIT!


#ifndef LILI_AUDIO_MESSAGE_RECOGNIZESPEECH_H
#define LILI_AUDIO_MESSAGE_RECOGNIZESPEECH_H

#include <ros/service_traits.h>


#include <lili_audio/RecognizeSpeechRequest.h>
#include <lili_audio/RecognizeSpeechResponse.h>


namespace lili_audio
{

struct RecognizeSpeech
{

typedef RecognizeSpeechRequest Request;
typedef RecognizeSpeechResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecognizeSpeech
} // namespace lili_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lili_audio::RecognizeSpeech > {
  static const char* value()
  {
    return "0f212b08e2dfacb9148fa1a62023e9ac";
  }

  static const char* value(const ::lili_audio::RecognizeSpeech&) { return value(); }
};

template<>
struct DataType< ::lili_audio::RecognizeSpeech > {
  static const char* value()
  {
    return "lili_audio/RecognizeSpeech";
  }

  static const char* value(const ::lili_audio::RecognizeSpeech&) { return value(); }
};


// service_traits::MD5Sum< ::lili_audio::RecognizeSpeechRequest> should match 
// service_traits::MD5Sum< ::lili_audio::RecognizeSpeech > 
template<>
struct MD5Sum< ::lili_audio::RecognizeSpeechRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lili_audio::RecognizeSpeech >::value();
  }
  static const char* value(const ::lili_audio::RecognizeSpeechRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lili_audio::RecognizeSpeechRequest> should match 
// service_traits::DataType< ::lili_audio::RecognizeSpeech > 
template<>
struct DataType< ::lili_audio::RecognizeSpeechRequest>
{
  static const char* value()
  {
    return DataType< ::lili_audio::RecognizeSpeech >::value();
  }
  static const char* value(const ::lili_audio::RecognizeSpeechRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lili_audio::RecognizeSpeechResponse> should match 
// service_traits::MD5Sum< ::lili_audio::RecognizeSpeech > 
template<>
struct MD5Sum< ::lili_audio::RecognizeSpeechResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lili_audio::RecognizeSpeech >::value();
  }
  static const char* value(const ::lili_audio::RecognizeSpeechResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lili_audio::RecognizeSpeechResponse> should match 
// service_traits::DataType< ::lili_audio::RecognizeSpeech > 
template<>
struct DataType< ::lili_audio::RecognizeSpeechResponse>
{
  static const char* value()
  {
    return DataType< ::lili_audio::RecognizeSpeech >::value();
  }
  static const char* value(const ::lili_audio::RecognizeSpeechResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LILI_AUDIO_MESSAGE_RECOGNIZESPEECH_H
