// Generated by gencpp from file lili_audio/TTSGoal.msg
// DO NOT EDIT!


#ifndef LILI_AUDIO_MESSAGE_TTSGOAL_H
#define LILI_AUDIO_MESSAGE_TTSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lili_audio
{
template <class ContainerAllocator>
struct TTSGoal_
{
  typedef TTSGoal_<ContainerAllocator> Type;

  TTSGoal_()
    : speech()
    , filepath()
    , voice()  {
    }
  TTSGoal_(const ContainerAllocator& _alloc)
    : speech(_alloc)
    , filepath(_alloc)
    , voice(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _speech_type;
  _speech_type speech;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filepath_type;
  _filepath_type filepath;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _voice_type;
  _voice_type voice;




  typedef boost::shared_ptr< ::lili_audio::TTSGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lili_audio::TTSGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TTSGoal_

typedef ::lili_audio::TTSGoal_<std::allocator<void> > TTSGoal;

typedef boost::shared_ptr< ::lili_audio::TTSGoal > TTSGoalPtr;
typedef boost::shared_ptr< ::lili_audio::TTSGoal const> TTSGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lili_audio::TTSGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lili_audio::TTSGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lili_audio

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'lili_audio': ['/home/christie/catkin_ws/devel/share/lili_audio/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lili_audio::TTSGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lili_audio::TTSGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lili_audio::TTSGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lili_audio::TTSGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lili_audio::TTSGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lili_audio::TTSGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lili_audio::TTSGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69cdb2a3c22edb952c9d7579f657a5a8";
  }

  static const char* value(const ::lili_audio::TTSGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69cdb2a3c22edb95ULL;
  static const uint64_t static_value2 = 0x2c9d7579f657a5a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lili_audio::TTSGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lili_audio/TTSGoal";
  }

  static const char* value(const ::lili_audio::TTSGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lili_audio::TTSGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string speech\n\
string filepath\n\
string voice\n\
";
  }

  static const char* value(const ::lili_audio::TTSGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lili_audio::TTSGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speech);
      stream.next(m.filepath);
      stream.next(m.voice);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TTSGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lili_audio::TTSGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lili_audio::TTSGoal_<ContainerAllocator>& v)
  {
    s << indent << "speech: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.speech);
    s << indent << "filepath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filepath);
    s << indent << "voice: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.voice);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LILI_AUDIO_MESSAGE_TTSGOAL_H
