// Generated by gencpp from file lili_audio/TTSResult.msg
// DO NOT EDIT!


#ifndef LILI_AUDIO_MESSAGE_TTSRESULT_H
#define LILI_AUDIO_MESSAGE_TTSRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lili_audio
{
template <class ContainerAllocator>
struct TTSResult_
{
  typedef TTSResult_<ContainerAllocator> Type;

  TTSResult_()
    {
    }
  TTSResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::lili_audio::TTSResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lili_audio::TTSResult_<ContainerAllocator> const> ConstPtr;

}; // struct TTSResult_

typedef ::lili_audio::TTSResult_<std::allocator<void> > TTSResult;

typedef boost::shared_ptr< ::lili_audio::TTSResult > TTSResultPtr;
typedef boost::shared_ptr< ::lili_audio::TTSResult const> TTSResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lili_audio::TTSResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lili_audio::TTSResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lili_audio

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lili_audio': ['/home/christie/catkin_ws/devel/share/lili_audio/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lili_audio::TTSResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lili_audio::TTSResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lili_audio::TTSResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lili_audio::TTSResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lili_audio::TTSResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lili_audio::TTSResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lili_audio::TTSResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::lili_audio::TTSResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::lili_audio::TTSResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lili_audio/TTSResult";
  }

  static const char* value(const ::lili_audio::TTSResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lili_audio::TTSResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
";
  }

  static const char* value(const ::lili_audio::TTSResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lili_audio::TTSResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TTSResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lili_audio::TTSResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::lili_audio::TTSResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LILI_AUDIO_MESSAGE_TTSRESULT_H
