build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python35"
    - PYTHON: "C:/Python36"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - "%PYTHON%/python.exe -m pip install wheel"
  - "%PYTHON%/python.exe -m pip install -e ."
  # Install ffmpeg
  - ps: Start-FileDownload ('http://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-latest-win64-shared.7z') ffmpeg-shared.7z
  - 7z x ffmpeg-shared.7z > NULL
  - "SET PATH=%cd%\\ffmpeg-latest-win64-shared\\bin;%PATH%"
test_script:
  - "%PYTHON%/python.exe test/test.py"
